# -*- coding: utf-8 -*-
"""Pyhton Final Ödevi OOS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nDYZckiAAnNWwDsCAilv50aZZEd8DUkm
"""

#@title Phyton Final Projesi (OOS)

from abc import ABC, abstractmethod

class Kaynak(ABC):
    def __init__(self, baslik, kayitNo):
       # Self bizm değişkenimizi temsil eder.
       # Burası setter'ı tetikler.
        self.baslik = baslik
        self.kayitNo = kayitNo

    # Metodumuzu değişken gibi gösterir.[baslik() = baslik]
    @property
    def baslik(self):
        return self._baslik
    # Medonumuza veri gelmeden önce kontrolünü yapar çünkü metodumuz değişken gibi tanımlanabiliyor.
    @baslik.setter
    def baslik(self, baslik):
        self._baslik = baslik

    @property
    def kayitNo(self):
        return self._kayitNo

    @kayitNo.setter
    def kayitNo(self, kayitNo):
        self._kayitNo = kayitNo

#__________________________________________________________________________________________________________________________________

class Kitap(Kaynak):
    def __init__(self, baslik, kayitNo, yazar, sayfa_sayisi):

      # super().__init__() kullanarak üst sınıfın (Kaynak) özelliklerini alıyoruz.
        super().__init__(baslik, kayitNo)

      # Kitaba özel özellikler.
        self.yazar = yazar
        self.sayfa_sayisi = sayfa_sayisi


    @property
    def yazar(self):
        return self._yazar

    @yazar.setter
    def yazar(self, yazar):
        self._yazar = yazar

    @property
    def sayfa_sayisi(self):
        return self._sayfa_sayisi

    @sayfa_sayisi.setter
    def sayfa_sayisi(self, sayfa_sayisi):
        self._sayfa_sayisi = sayfa_sayisi

#__________________________________________________________________________________________________________________________________

class Dergi(Kaynak):
    def __init__(self, baslik, kayitNo, yayin_donemi, sayi_no):

      # super() ile üst sınıfın özelliklerini çektik.
        super().__init__(baslik, kayitNo)

        # Dergiye özel özellikler
        self.yayin_donemi = yayin_donemi
        self.sayi_no = sayi_no

    @property
    def yayin_donemi(self):
        return self._yayin_donemi

    @yayin_donemi.setter
    def yayin_donemi(self, yayin_donemi):
        self._yayin_donemi = yayin_donemi

    @property
    def sayi_no(self):
        return self._sayi_no

    @sayi_no.setter
    def sayi_no(self, sayi_no):
        self._sayi_no = sayi_no

#__________________________________________________________________________________________________________________________________

# Ekle, sil, güncelle, listele metodlarının şablonu. (abstractmethod)
class Islem(ABC):

    # Kendisinden miras alınacak olan özellikler var mı kontrolünü yapar. (abstractmethod)
    @abstractmethod
    def ekle(self):
        pass

    @abstractmethod
    def sil(self):
        pass

    @abstractmethod
    def guncelle(self):
        pass

    @abstractmethod
    def listele(self):
        pass

#__________________________________________________________________________________________________________________________________

class KitapIslem(Islem):
    def __init__(self):

        # Kitapları RAM'de tutacağımız listemiz.
        self.kitap_listesi = []

    def ekle(self):

        # print() menü daha düzenli gözükmesi için bolşuk koyar.
        print()
        print("--- Kitap Ekle ---")
        kayitNo = input("Kitabın kayıt numarasını girin: ")

        # Kayıt no kontrol sistemi.
        # Class içerisine adam yolluyoruz (k) bizim için kayıtNo kısmına bakıyor bu nedenle "k.kayitNo yazarak veriye ulaşıyoruz.
        # Fakat class icerisinde self.kayıtNo yazarak ulaşabiliriz zaten içerideyiz.
        for k in self.kitap_listesi:
            if k.kayitNo == kayitNo:
                print("HATA: Bu kayıt numarası zaten sistemde var!")
                return

        # Veri girişi.
        baslik = input("Kitabın başlığını girin: ")
        yazar = input("Kitabın yazarını girin: ")
        sayfa = input("Kitabın sayfa sayısını girin: ")

        yeni_kitap = Kitap(baslik, kayitNo, yazar, sayfa)

        # append kullanarak listemize veri ekliyoruz.
        self.kitap_listesi.append(yeni_kitap)
        print("Kitap başarıyla eklendi.")

    def sil(self):
        print()
        print("--- Kitap Sil ---")
        kayitNo = input("Silinecek kitabın kayıt numarasını girin: ")
        for silinecekKitap in self.kitap_listesi:
            if silinecekKitap.kayitNo == kayitNo:

                # remove kullanarak veriyi listeden siliyoruz.
                self.kitap_listesi.remove(silinecekKitap)
                print("Kitap başarıyla silindi.")
                return
        print("Kayıt bulunamadı.")

    def guncelle(self):
        print()
        print("--- Kitap Güncelle ---")
        kayitNo = input("Güncellenecek kitabın kayıt numarasını girin: ")
        for kitap in self.kitap_listesi:
            if kitap.kayitNo == kayitNo:
                print("Yeni bilgileri girin (Değiştirmek istemiyorsanız boş bırakıp Enter'a basın):")
                yeni_baslik = input(f"Yeni Başlık ({kitap.baslik}): ")
                if yeni_baslik: kitap.baslik = yeni_baslik

                yeni_yazar = input(f"Yeni Yazar ({kitap.yazar}): ")
                if yeni_yazar: kitap.yazar = yeni_yazar

                yeni_sayfa = input(f"Yeni Sayfa Sayısı ({kitap.sayfa_sayisi}): ")
                if yeni_sayfa: kitap.sayfa_sayisi = yeni_sayfa

                print("Kitap başarıyla güncellendi.")
                return
        print("Kayıt bulunamadı.")

    def listele(self):
        print()
        print("--- Kitap Listesi ---")

        # Liste boşken uyarı verme sistemi.
        if not self.kitap_listesi:
            print("Kayıt bulunamadı.")
            return

        for kitap in self.kitap_listesi:
            print(f"Kayıt No: {kitap.kayitNo} | Başlık: {kitap.baslik} | Yazar: {kitap.yazar} | Sayfa: {kitap.sayfa_sayisi}")

#__________________________________________________________________________________________________________________________________

# Kitap işlemlerinin dergi versiyonu.
class DergiIslem(Islem):
    def __init__(self):
        self.dergi_listesi = []

    def ekle(self):
        print()
        print("--- Dergi Ekle ---")
        kayitNo = input("Derginin kayıt numarasını girin: ")

        for d in self.dergi_listesi:
            if d.kayitNo == kayitNo:
                print("HATA: Bu kayıt numarası zaten sistemde var!")
                return

        baslik = input("Derginin başlığını girin: ")
        yayin_donemi = input("Yayın dönemini girin (Aylık/Haftalık vb.): ")
        sayi_no = input("Sayı numarasını girin: ")

        yeni_dergi = Dergi(baslik, kayitNo, yayin_donemi, sayi_no)
        self.dergi_listesi.append(yeni_dergi)
        print("Dergi başarıyla eklendi.")

    def sil(self):
        print()
        print("--- Dergi Sil ---")
        kayitNo = input("Silinecek derginin kayıt numarasını girin: ")
        for dergi in self.dergi_listesi:
            if dergi.kayitNo == kayitNo:
                self.dergi_listesi.remove(dergi)
                print("Dergi başarıyla silindi.")
                return
        print("Kayıt bulunamadı.")

    def guncelle(self):
        print()
        print("--- Dergi Güncelle ---")
        kayitNo = input("Güncellenecek derginin kayıt numarasını girin: ")
        for dergi in self.dergi_listesi:
            if dergi.kayitNo == kayitNo:
                yeni_baslik = input(f"Yeni Başlık ({dergi.baslik}): ")
                if yeni_baslik: dergi.baslik = yeni_baslik

                yeni_donem = input(f"Yeni Yayın Dönemi ({dergi.yayin_donemi}): ")
                if yeni_donem: dergi.yayin_donemi = yeni_donem

                yeni_sayi = input(f"Yeni Sayı No ({dergi.sayi_no}): ")
                if yeni_sayi: dergi.sayi_no = yeni_sayi

                print("Dergi başarıyla güncellendi.")
                return
        print("Kayıt bulunamadı.")

    def listele(self):
        print()
        print("--- Dergi Listesi ---")
        if not self.dergi_listesi:
            print("Kayıt bulunamadı.")
            return

        for dergi in self.dergi_listesi:
            print(f"Kayıt No: {dergi.kayitNo} | Başlık: {dergi.baslik} | Dönem: {dergi.yayin_donemi} | Sayı: {dergi.sayi_no}")

#__________________________________________________________________________________________________________________________________

class Menu:
    def goster(self):
        print()
        print("=== KÜTÜPHANE YÖNETİM SİSTEMİ ===")
        print("1. Kitap Ekle")
        print("2. Kitap Sil")
        print("3. Kitap Güncelle")
        print("4. Kitapları Listele")
        print("5. Dergi Ekle")
        print("6. Dergi Sil")
        print("7. Dergi Güncelle")
        print("8. Dergileri Listele")
        print("9. Çıkış")

# Sınıflarımızdan yöneticilerimizi (nesneleri) oluşturduk ki kullanılabilsinler.
kitap_yoneticisi = KitapIslem()
dergi_yoneticisi = DergiIslem()
ana_menu = Menu()

# Menüyü sürekli gösterecek olan while true döngüsü.
# While true ile sonusza kadar döngüde brakıyoruz yani çıkışları elimizde tutuyoruz.
while True:
    ana_menu.goster()
    secim = input("Yapmak istediğiniz işlemi seçin (1-9): ")

    if secim == '1':
        kitap_yoneticisi.ekle()
    elif secim == '2':
        kitap_yoneticisi.sil()
    elif secim == '3':
        kitap_yoneticisi.guncelle()
    elif secim == '4':
        kitap_yoneticisi.listele()
    elif secim == '5':
        dergi_yoneticisi.ekle()
    elif secim == '6':
        dergi_yoneticisi.sil()
    elif secim == '7':
        dergi_yoneticisi.guncelle()
    elif secim == '8':
        dergi_yoneticisi.listele()
    elif secim == '9':
        print("Sistemden çıkılıyor. İyi günler!")
        break
    else:
        print("Hatalı giriş yaptınız! Lütfen 1-9 arası bir sayı girin.")
